import requests
from bs4 import BeautifulSoup
import csv
import re


pagesteste=['https://santander.com.br',
'https://santander.com.br/atendimento-para-voce/simuladores/simulador-credito-imobiliario',
'https://santander.com.br/atendimento-para-voce/acesso-nao-correntista',
'https://santander.com.br/atendimento-para-voce/boletos',
'https://santander.com.br/atendimento-para-voce/internet-banking',
'https://santander.com.br/atendimento-para-voce/fale-com-o-santander',
'https://santander.com.br/conversa-seguros-proteger-familia-preocupacao-pouco',
'https://santander.com.br/atendimento-empresas/modelos-de-atendimento/negocios-direct',
'https://santander.com.br/servicos-financeiros/solucoes-de-recebimento/recolhimento-de-valores',
'https://santander.com.br/creditos-e-financiamentos-para-empresas/expansao-de-negocios/cartao-bndes',
'https://santander.com.br/global-corporate-banking',
'https://santander.com.br/creditos-e-financiamentos/para-voce',
'https://santander.com.br/creditos-e-financiamentos',
'https://santander.com.br/creditos-e-financiamentos-para-empresas',
'https://santander.com.br/investimentos-e-previdencia/reserva-de-emergencia',
'https://santander.com.br/investimentos-e-previdencia/investimentos-private-banking',
'https://santander.com.br/investimentos-e-previdencia',
'https://santander.com.br/conta-corrente-pessoa-fisica/servicos/contamax-pf',
'https://santander.com.br/creditos-e-financiamentos-para-empresas/antecipacao-de-recebiveis/desconto-de-duplicatas',
'https://santander.com.br/comercio-exterior-e-cambio/cambio/cambio-futuro',
'https://santander.com.br/comercio-exterior-e-cambio/servicos-internacionais/assinatura-digital',
'https://santander.com.br/getnet',
'https://santander.com.br/seguros/assistencia-24-horas',
'https://santander.com.br/institucional-santander',
'https://santander.com.br/investimentos/produtos-da-corretora',
'https://santander.com.br/institucional-santander/fornecedores',
'https://santander.com.br/institucional-santander/cultura/o-que-voce-encontra',
'https://santander.com.br/cartoes-descontinuados',
'https://santander.com.br/campanhas/microcredito',
'https://santander.com.br/cambio/moeda-estrangeira-em-especie',
'https://santander.com.br/creditos-e-financiamentos/para-veiculos-e-maquinas/financiamento-de-veiculos',
'https://santander.com.br/creditos-e-financiamentos/para-voce/credito-com-veiculo-como-garantia',
'https://santander.com.br/agronegocio/protecao-para-os-seus-negocios/seguro-colheita-protegida',
'https://santander.com.br/creditos-e-financiamentos/para-voce/credito-pessoal',
'https://santander.com.br/analise-economica/relatorio-diario-de-economia-e-mercados',
'https://santander.com.br/conheca-novo-site',
'https://santander.com.br/campanhas/seguro-protecao-residencial-sl-apartamento',
'https://santander.com.br/campanhas/seguro-protecao-residencial-25off-para-minha-casa',
'https://santander.com.br/investimentos-e-previdencia/fundos-imobiliarios',
'https://santander.com.br/investimentos-e-previdencia/carteira-perfil-moderado',
'https://santander.com.br/conta-pessoa-juridica/santander-mais-gestao',
'https://santander.com.br/investimentos-e-previdencia/etfs',
'https://santander.com.br/investimentos-e-previdencia/opcoes',
'https://santander.com.br/capitalizacao/din-din-do-milhao',
'https://santander.com.br/campanhas-financeira',
'https://santander.com.br/campanhas/conta-ole',
'https://santander.com.br/universidades/emprego',
'https://santander.com.br/sustentabilidade/gestao-de-atividades/construcao-sustentavel',
'https://santander.com.br/campanhas/acesso-wifi',
'https://santander.com.br/amigodevalor/educar-transformar',
'https://santander.com.br/consorcio',
'https://santander.com.br/sustentabilidade/negocios-socioambientais/empreendedorismo',
'https://santander.com.br/creditos-e-financiamentos/para-voce/portabilidade-credito-consignado',
'https://santander.com.br/campanhas/seguros',
'https://santander.com.br/capitalizacao',
'https://santander.com.br/sustentabilidade/noticias/resultados-historicos',
'https://santander.com.br/educacao-financeira/tem-um-plano-definido',
'https://santander.com.br/seguros/seguro-viagem/como-contratar',
'https://santander.com.br/campanhas/marinha',
'https://santander.com.br/campanhas/renegociacao-sem-alcada-pessoa-juridica',
'https://santander.com.br/sustentabilidade/central-de-resultados',
'https://santander.com.br/campanhas/pais',
'https://santander.com.br/seguros/para-cartao/seguro-cartao-mais',
'https://santander.com.br/campanhas/pais/cartoes',
'https://santander.com.br/campanhas/pais/veiculos',
'https://santander.com.br/campanhas/pais/seguros',
'https://santander.com.br/investimentos',
'https://santander.com.br/cartoes-santander/solucoes-de-pagamento/parcelamento-de-fatura',
'https://santander.com.br/educacao-financeira',
'https://santander.com.br/amigodevalor/transformando-realidades',
'https://santander.com.br/tjsp',
'https://santander.com.br/seguros/para-voce/seguro-funeral',
'https://santander.com.br/cartoes-correspondentes-bancarios',
'https://santander.com.br/servicos-financeiros/solucoes-de-recebimento/debito-automatico',
'https://santander.com.br/servicos-financeiros/folha-de-pagamentos',
'https://santander.com.br/servicos-financeiros/solucoes-para-gestao-de-caixa/conta-escrow',
'https://santander.com.br/sustainability/employees/health-and-safety',
'https://santander.com.br/seguros/para-voce/seguro-renda-medicos',
'https://santander.com.br/ofertas-publicas/material-publicitario/rumo-sa',
'https://santander.com.br/cartoes-pessoa-juridica/gestao-de-negocios',
'https://santander.com.br/consorcio-portal-consorciado',
'https://santander.com.br/sustentabilidade/noticias/santander-sustentavel-mundo-dow-jones',
'https://santander.com.br/sustentabilidade/noticia/adolescentes-encontram-uma-estrela-guia',
'https://santander.com.br/campanhas/universidades',
'https://santander.com.br/educacao-financeira/nome-negativado',
'https://santander.com.br/educacao-financeira/negociacao-orientacao',
'https://santander.com.br/educacao-financeira/decimo-terceiro-salario',
'https://santander.com.br/agronegocio/protecao-para-os-seus-negocios/seguro-granizo',
'https://santander.com.br/agronegocio/financiamentos-do-bndes/moderfrota',
'https://santander.com.br/agronegocio/protecao-para-os-seus-negocios',
'https://santander.com.br/atendimento-para-voce/boletos/renegociacao-de-dividas',
'https://santander.com.br/cartoes-santander/servicos-e-informacoes/cancelamento-de-compra',
'https://santander.com.br/cartao-credito-santander',
'https://santander.com.br/conta-pessoa-juridica',
'https://santander.com.br/novas-regras-cheque-especial/quem-nao-recebe-salario-santander',
'https://santander.com.br/comercio-exterior-e-cambio/exportacao/carta-de-credito-de-exportacao',
'https://santander.com.br/comercio-exterior-e-cambio/importacao/carta-de-credito-de-importacao',
'https://santander.com.br/comercio-exterior-e-cambio/servicos-internacionais/conta-internacional',
'https://santander.com.br/institucional-santander/seguranca/golpe-da-ajuda',
'https://santander.com.br/institucional-santander/seguranca/boletos-falsos',
'https://santander.com.br/educacao-financeira/ano-novo',
'https://santander.com.br/lead/cc-aa-gold',
'https://santander.com.br/institucional-santander/',
'https://santander.com.br/atendimento-empresas/modelos-de-atendimento/nucleos-atendimento-empresas/',
'https://santander.com.br/cartao-credito-santander?ic=header-cartoes',
'https://santander.com.br/cambio/moeda-estrangeira-em-especie/',
'https://santander.com.br/creditos-e-financiamentos/para-veiculos-e-maquinas',
'https://santander.com.br/gestao-de-risco-financeiro/swaps/',
'https://santander.com.br/investimentos-e-previdencia/',
'https://santander.com.br/investimentos/planejamento-para-12-meses/cdb-di#condicoes',
'https://santander.com.br/investimentos/',
'https://santander.com.br/seguro-empresarial/para-emprestimo/seguro-capital-giro-protegido/',
'https://santander.com.br/cartoes-santander/santander-pass/',
'https://santander.com.br/cartoes-santander/solucoes-de-pagamento/total-parcelado/',
'https://santander.com.br/institucional-santander/cultura/',
'https://santander.com.br/assessoria-financeira-e-mercado-de-capitais/ofertas-publicas/ofertas-concluidas',
'https://santander.com.br/lead/cc-free',
'https://santander.com.br/demais-cartoes',
'https://santander.com.br/comercio-exterior-e-cambio/servicos-internacionais/cobranca-documentaria/',
'https://santander.com.br/creditos-e-financiamentos/para-veiculos-e-maquinas/financiamento-de-veiculos/',
'https://santander.com.br/servicos-financeiros/solucoes-para-gestao-de-caixa/cash-balance/',
'https://santander.com.br/servicos-financeiros/solucoes-de-recebimento/recolhimento-de-valores/']

for pg in pagesteste:
    page = requests.get(pg)
    soup = BeautifulSoup(page.text, 'html.parser')
    [x.extract() for x in soup.findAll('script')]
    teste = soup.find_all("a", href=re.compile("utm_source"))
    print(teste)
    print(page)
    if teste != []:
        teste = "Sim"
    else:
        teste = "Não"
    wtr = csv.writer(open('utm2.csv', 'a'), delimiter=',', lineterminator='\n')
    wtr.writerow([teste, pg])

print('done')